const TYPES = {
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_WEAPONS_COUNT: "GET_WEAPONS_COUNT",
  GET_PRODUCTS_COUNT: "GET_PRODUCTS_COUNT",
  ADD_PRODUCT: "ADD_PRODUCT",
  REMOVE_PRODUCT: "REMOVE_PRODUCT",
  GET_ORDERS: "GET_ORDERS",
  GET_CATEGORIES: "GET_CATEGORIES",
  ADD_CATEGORY: "ADD_CATEGORY",
  RM_CATEGORY: "RM_CATEGORY",
  GET_CART: "GET_CART",
  ADD_TO_CART: "ADD_TO_CART",
  RM_FROM_CART: "RM_FROM_CART",
  UPDATE_FORM: "UPDATE_FORM",
  CLEAR_FORM: "CLEAR_FORM",
  GET_USER: "GET_USER",
  SET_ORDER: "SET_ORDER",
  CLEAR_USER: "CLEAR_USER",
  UPDATE_INPUT: "UPDATE_INPUT",
  CLEAR_INPUT: "CLEAR_INPUT",
  CLEAR_CART: "CLEAR_CART",
};

module.exports = TYPES;
