const TYPES = {
    GET_PRODUCTS : 'GET_PRODUCTS',
    ADD_PRODUCT : 'ADD_PRODUCT',
    REMOVE_PRODUCT : 'REMOVE_PRODUCT',
    GET_ORDERS:'GET_ORDERS',
    GET_CATEGORIES : 'GET_CATEGORIES',
    ADD_CATEGORY: 'ADD_CATEGORY',
    RM_CATEGORY : 'RM_CATEGORY',
    GET_CART:'GET_CART',
    ADD_TO_CART : 'ADD_TO_CART',
    RM_FROM_CART : 'RM_FROM_CART',
    UPDATE_FORM:'UPDATE_FORM',
    CLEAR_FORM:'CLEAR_FORM'
}

module.exports = TYPES